CSS code improvements
krman009/androidtemplate pull request #1
Opened 2019-10-01 10:48 UTC by juhilsomaiya

Css code fixes.

2019-10-02 19:32 UTC, krman009 requested changes
Please push with requested changes, I'll merge it ;) @juhilsomaiya

2019-10-02 19:32 UTC, krman009 commented on style.css
> +  transition: all .7s ease-in-out
We can remove the prefixes as per [Can I use](https://caniuse.com/#feat=css-transitions).
Please remove the lines other than last one.

2019-10-02 19:32 UTC, krman009 commented on style.css
> +  background: -o-linear-gradient(top, rgba(255, 0, 255, .3), rgba(8, 180, 80, .1), rgba(180, 80, 80, .1), rgba(0, 255, 255, .3), rgba(8, 180, 80, .1), rgba(180, 80, 80, .1), rgba(255, 0, 255, .3), rg
Remove these two lines as we do not need this anymore.

2019-10-02 19:32 UTC, krman009 commented on style.css
> +  background: -ms-linear-gradient(bottom, rgba(0, 0, 0, .1), rgba(0, 0, 0, .3), #000, rgba(0, 0, 0, .2), rgba(0, 0, 0, .1), #000, rgba(0, 0, 0, .2), rgba(0, 0, 0, .1), #000);
Remove these two lines too.

2019-10-02 19:32 UTC, krman009 commented on style.css
> +  -ms-transition: .5s
Remove Lines: 110, 112, 113 and 114.

2019-10-02 19:32 UTC, krman009 commented on style.css
> +  background: -ms-linear-gradient(bottom, rgba(110, 110, 110, .1), rgba(110, 110, 110, .3), #6e6e6e, rgba(110, 110, 110, .2), rgba(110, 110, 110, .1), #6e6e6e, rgba(110, 110, 110, .2), rgba(110, 110,
Remove these two lines too.

2019-10-02 19:32 UTC, krman009 commented on style.css
> +  background: -ms-radial-gradient(top, #009 10%, transparent 80%);
Remove these lines.

2019-10-02 19:32 UTC, krman009 commented on style.css
> +  -ms-transition: .5s;
Remove prefixed lines.

2019-10-02 19:32 UTC, krman009 commented on style.css
> +  background: -ms-radial-gradient(top, #009 10%, transparent 80%);
Remove these lines too.

2019-10-14 06:55 UTC, juhilsomaiya commented on style.css
> +  background: -ms-radial-gradient(top, #009 10%, transparent 80%);
@krman009 can you please check ?

2019-10-15 07:32 UTC, krman009 approved these changes
Thanks buddy @juhilsomaiya :+1:

2019-10-15 07:34 UTC, merged